spring:
  application:
    name: config-client
  cloud:
    config:
      uri: http://localhost:8769    #指定读取配置文件地址
      fail-fast: true               #是否开启快速失败
  profiles:
    active: dev                     #指定配置文件开发环境
